language: cpp
compiler: 
  - gcc
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "bin/godot.x11.tools.64"
  skip_cleanup: true
  on:
    tags: true
before_install:
  

before_script: 
  - export TARGET_ARCH='x86'
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq scons pkg-config libx11-dev libxcursor-dev build-essential libasound2-dev libfreetype6-dev libgl1-mesa-dev libglu-dev  
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  
script: scons platform=x11
